apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aish
  name: aish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-app
  template:
    metadata:
      labels:
        app: emp-app-label
    spec:
      containers:
      - name: emp-app-cont
        image: 937184064551.dkr.ecr.us-east-1.amazonaws.com/humanresource
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
