apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-management
  template:
    metadata:
      labels:
        app: employee-management
    spec:
      containers:
      - name: employee-management
        image: 937184064551.dkr.ecr.us-east-1.amazonaws.com/humanresource
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
